apiVersion: batch/v1
kind: CronJob
metadata:
  name: python-cronjob
spec:
  schedule: "*/2 * * * *"  # Every 2 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: python-cronjob
            image: robinbuezo11/sa-p5-cronjob:latest
            resources:
              requests:
                memory: "16Mi"
                cpu: "25m"
              limits:
                memory: "32Mi"
                cpu: "50m"
          restartPolicy: OnFailure